// apps/web/src/app/layout.tsx
import { PublicLayout } from '@/components/layout/PublicLayout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'MVP Base',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return <PublicLayout>{children}</PublicLayout>;
}
