// apps/web/src/app/layout.tsx
import { Toaster } from '@/components/ui/sonner';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'MVP Base',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang='en' className={montserrat.variable} suppressHydrationWarning>
        <body className='font-sans antialiased'>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
